package com.example.to_do.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)



// Light Theme Colors
val md_theme_light_primary = Color(0xFF006C51)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF8AF8D5)
val md_theme_light_onPrimaryContainer = Color(0xFF002116)
val md_theme_light_secondary = Color(0xFF4B635A)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCEE9DD)
val md_theme_light_onSecondaryContainer = Color(0xFF082018)
val md_theme_light_tertiary = Color(0xFF416277)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC5E7FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001E2D)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFDF9)
val md_theme_light_onBackground = Color(0xFF191C1B)
val md_theme_light_surface = Color(0xFFFBFDF9)
val md_theme_light_onSurface = Color(0xFF191C1B)
val md_theme_light_surfaceVariant = Color(0xFFDBE5DE)
val md_theme_light_onSurfaceVariant = Color(0xFF404944)
val md_theme_light_outline = Color(0xFF707973)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1EE)
val md_theme_light_inverseSurface = Color(0xFF2E312F)
val md_theme_light_inversePrimary = Color(0xFF6DDBBA)

// Dark Theme Colors
val md_theme_dark_primary = Color(0xFF6DDBBA)
val md_theme_dark_onPrimary = Color(0xFF003829)
val md_theme_dark_primaryContainer = Color(0xFF00513C)
val md_theme_dark_onPrimaryContainer = Color(0xFF8AF8D5)
val md_theme_dark_secondary = Color(0xFFB2CCC1)
val md_theme_dark_onSecondary = Color(0xFF1E352C)
val md_theme_dark_secondaryContainer = Color(0xFF344C43)
val md_theme_dark_onSecondaryContainer = Color(0xFFCEE9DD)
val md_theme_dark_tertiary = Color(0xFFA9CBE3)
val md_theme_dark_onTertiary = Color(0xFF0C3446)
val md_theme_dark_tertiaryContainer = Color(0xFF274A5F)
val md_theme_dark_onTertiaryContainer = Color(0xFFC5E7FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1B)
val md_theme_dark_onBackground = Color(0xFFE1E3E0)
val md_theme_dark_surface = Color(0xFF191C1B)
val md_theme_dark_onSurface = Color(0xFFE1E3E0)
val md_theme_dark_surfaceVariant = Color(0xFF404944)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC9C2)
val md_theme_dark_outline = Color(0xFF89938D)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1B)
val md_theme_dark_inverseSurface = Color(0xFFE1E3E0)
val md_theme_dark_inversePrimary = Color(0xFF006C51)

// Success colors
val md_theme_light_success = Color(0xFF006E1C)
val md_theme_light_onSuccess = Color(0xFFFFFFFF)
val md_theme_light_successContainer = Color(0xFFA1F699)
val md_theme_light_onSuccessContainer = Color(0xFF002204)

val md_theme_dark_success = Color(0xFF86D880)
val md_theme_dark_onSuccess = Color(0xFF00390C)
val md_theme_dark_successContainer = Color(0xFF005314)
val md_theme_dark_onSuccessContainer = Color(0xFFA1F699)